engines/base_account/config/routes.rb
BaseAccount::Engine.routes.draw do
  scope module: :user do
    get    "password_reset"        => "password_reset#new"
    post   "password_reset"        => "password_reset#create"
    get    "password_reset/:token" => "password_reset#edit",
                                      as: "do_password_reset"
    post   "password_reset/:token" => "password_reset#update"

    get   "/profile/:id", to: "profile#show", as: "profile"
    put   "/profile/:id", to: "profile#update"
    patch "/profile/:id", to: "profile#update"
  end
end

engines/base_account/app/controllers/base_account/application_controller.rb
module BaseAccount
  class ApplicationController < ::ApplicationController
  end
end

engines/base_account/app/controllers/base_account/user/password_reset_controller.rb
module BaseAccount
  module User
    class PasswordResetController < BaseAccount::ApplicationController

      def new
        @form = RequestPasswordReset.run!
      end


      def create
        inputs =
          params[:user_request_password_reset_password_reset]
        request_form =
          CreateRequestPasswordReset.run(inputs)
        if request_form.valid?
          flash[:notice] =
            t("flash.user.request_password_reset.create.success_html",
            email: request_form.email).html_safe
          redirect_to main_app.root_path
        else
          flash.now[:alert] =
            t("flash.user.request_password_reset.create.failure")
          @form = RequestPasswordReset.run!
          render "new"
        end
      end


      def edit
        @form = EditPasswordReset.run!
      end


      def update
        password =
          params[:user_edit_password_reset_password_reset][:password]
        token    = params[:token]
        inputs   = Hash[password: password, token: token]
        reset    = ResetPassword.run(inputs)
        if reset.valid?
          flash[:notice] = t("flash.user.password_reset.edit.success")
          redirect_to main_app.root_path
        else
          @form = EditPasswordReset.run!
          flash.now[:alert] = t("flash.user.password_reset.edit.failure")
          render "edit"
        end
      end
    end
  end
end

engines/base_account/app/controllers/base_account/user/profile_controller.rb
module BaseAccount
  module User
    class ProfileController < BaseAccount::ApplicationController

      before_action :login_user

      def show
        @form = find_user!
      end

      def update
        inputs  = { user: find_user! }.reverse_merge(params[:user])
        outcome = UpdateUser.run(inputs)

        if outcome.valid?
          flash[:notice] = t("flash.profile.update.success")
          redirect_to(profile_path(outcome.user.id))
        else
          flash.now[:alert] = t("flash.profile.update.failure")
          @form = find_user!
          render(:show)
        end
      end

      private

      def find_user!
        outcome = FindUser.run(params)

        if outcome.valid?
          outcome.result
        else
          raise ActionController::RoutingError.new("Not Found")
        end
      end
    end
  end
end

engines/base_account/app/views/base_account/user/password_reset/edit.html.slim
= content_for :angular_js do
  = javascript_include_tag("base_account/editPasswordResetCtrl")

.container
  .col-md-6.col-md-offset-3
    h1= t ".headline"

    = bootstrap_form_for @form, url: do_password_reset_path,
      html: {name: "editPasswordResetForm", novalidate: true} do |f|
      = f.password_field :password, label: t(".password_field_label"),
        data: {"ng-model" => "password", required: true, "ng-minlength" => 6}

      = f.submit t(".submit_password_reset_button"),
        id: "submit_password_reset", class: "btn btn-default",
        data: {"ng-disabled" => "editPasswordResetForm.$invalid"}

engines/base_account/app/views/base_account/user/password_reset/new.html.slim
= content_for :angular_js do
  = javascript_include_tag("base_account/requestPasswordResetCtrl")

.container
  .col-md-6.col-md-offset-3
    h1= t ".headline"

    = bootstrap_form_for @form, url: password_reset_path,
      html: {name: "requestPasswordResetForm", novalidate: true} do |f|
      = f.email_field :email, label: t(".email_field_label"),
        data: {"ng-model" => "email", required: true}

      = f.submit t(".submit_password_reset_request_button"),
        id: "submit_password_reset_request", class: "btn btn-default",
        data: {"ng-disabled" => "requestPasswordResetForm.$invalid"}

engines/base_account/app/views/base_account/user/profile/show.html.slim
= content_for :angular_js do
  = javascript_include_tag("base_account/profileCtrl")

.container ng-controller="profileCtrl"
  .col-md-6.col-md-offset-3
    h1= t ".headline"


    = bootstrap_form_for @form, url: profile_path,
      html: {name: "profileForm", novalidate: true} do |f|
      = f.email_field :email, label: t(".email_field_label"),
        placeholder: @form.email,
        data: {"ng-model" => "email"}

      = f.password_field :password, label: t(".new_password_field_label"),
        id: "newPasswordInput", data: {"ng-model" => "new_password",
        "ng-minlength" => 6}

      = f.password_field :password_confirmation,
        label: t(".password_confirmation_field_label"),
        id: "passwordConfirmationInput",
        data: {"ng-model" => "password_confirmation",
        "ng-required" => "profileForm.newPasswordInput.$touched",
        "ng-minlength" => 6, "toggle"=>"tooltip",
        "title" => t(".passwords_not_equal")}

      = f.button t(".submit_profile_button"),
        id: "submitProfile", class: "btn btn-default",
        data: {"ng-disabled" => \
        "profileForm.$invalid || notSamePasswords() || noFieldsSet()"}